adb shell pm uninstall -k --user 0 com.nttdocomo.android.msg
adb shell pm uninstall -k --user 0 com.nttdocomo.android.screenlockservice
adb shell pm uninstall -k --user 0 com.nttdocomo.android.databackup
adb shell pm uninstall -k --user 0 com.nttdocomo.android.pf.dcmippushaggregator
adb shell pm uninstall -k --user 0 com.nttdocomo.android.anshinsecurity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.schedulememo
adb shell pm uninstall -k --user 0 com.nttdocomo.android.pf.dcmwappush
adb shell pm uninstall -k --user 0 com.nttdocomo.android.applicationmanagersub
adb shell pm uninstall -k --user 0 com.nttdocomo.android.osv
adb shell pm uninstall -k --user 0 com.huawei.hw02l.manual
adb shell pm uninstall -k --user 0 com.nttdocomo.android.voiceeditor
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.carriermail
adb shell pm uninstall -k --user 0 com.rsupport.rs.activity.ntt
adb shell pm uninstall -k --user 0 com.huawei.numberidentity
adb shell pm uninstall -k --user 0 com.nttdocomo.android.phonemotion
adb shell pm uninstall -k --user 0 com.nttdocomo.android.sdcardbackup
adb shell pm uninstall -k --user 0 jp.dmapnavi.navi02
adb shell pm uninstall -k --user 0 com.nttdocomo.android.kittingmanager
adb shell pm uninstall -k --user 0 com.nttdocomo.keitai.payment
adb shell pm uninstall -k --user 0 com.nttdocomo.dcard
adb shell pm uninstall -k --user 0 com.nttdocomo.android.accountwipe
adb shell pm uninstall -k --user 0 jp.co.disney.apps.gm.disneydx
adb shell pm uninstall -k --user 0 com.nttdocomo.android.photocollection
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.dbook
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dpoint
adb shell pm uninstall -k --user 0 com.nttdocomo.android.store
adb shell pm uninstall -k --user 0 com.nttdocomo.android.dmenu2
adb shell pm uninstall -k --user 0 com.nttdocomo.android.mascot
adb shell pm uninstall -k --user 0 com.nttdocomo.android.mydocomo
adb shell pm uninstall -k --user 0 jp.co.nttdocomo.android.anshinmode
adb shell pm uninstall -k --user 0 com.nttdocomo.android.remotelock
adb shell pm uninstall -k --user 0 com.nttdocomo.android.voicetranslation
adb shell pm uninstall -k --user 0 com.nttdocomo.android.wipe
